CREATE TABLE INTEL_REPORTS
(
Map varchar(255) NOT NULL,
Intel_Report varchar(255),
Possible_Missions varchar(255),
Specialization varchar(25),
PRIMARY KEY (Map, Intel_Report)
);

INSERT into INTEL_REPORTS (Map, Intel_Report, Possible_Missions, Specialization) VALUES ('Tokyo Martial Law', 'A radio report suggests that enemy cover operatives are active in the area.', 'Il-76 and Escorts', 'Fighter'),
('Tokyo Martial Law', 'Elite enemy air forces are rapidly approaching.', 'T-50 / F-22 + F35 + YF 23', 'Fighter'),
('Tokyo Martial Law', 'Enemy jamming signals detected.', 'Stealth Destroyers', 'Multirole'),
('Tokyo Martial Law', 'Intelligence suggest that new enemy weapons are being transported in the area.', 'Scinfaxi / Stealth Destroyers', 'Attacker'),
('Tokyo Martial Law', 'The shadow of a large object has been confirmed out at sea.', 'Scinfaxi / Stealth Destroyers', 'Attacker'),
('Tokyo Martial Law', 'Locals residents have witnessed shadows of a large aircraft.', 'Il-76 and Escorts', 'Fighter'),
('Tokyo Martial Law', 'Multiple unidentified flying objects are approaching.', 'MiG-31 / SU-35 / F-22 + F35 + YF 23 / Meteorites / Il-76 and Escorts', 'Fighter'),
('Tokyo Martial Law', 'Radar sites in the vicinity have detected what it appears to be stealth aircraft.', 'F-22 + F35 + YF 23 / Stealth Destroyers', 'Multirole'),
('Tokyo Martial Law', 'Reports indicate that enemy air forces equipped with special missiles are now in the air.', 'MiG-31 / F-14D / SU-35', 'Fighter'),
('Aerospace Center Defense', 'Elite enemy air forces are rapidly approaching.', 'F-22 + F-35B + YF-23 / T-50', 'Fighter'),
('Aerospace Center Defense', 'Enemy jamming signals detected.', 'Il-76 and Escorts', 'Fighter'),
('Aerospace Center Defense', 'Intelligence suggests that new enemy weapons are being transported in the area.', 'Scinfaxi / B-2 Bombers / Kottos and Gyges', 'Multirole'),
('Aerospace Center Defense', 'Locals residents have witnessed shadows of a large aircraft.', 'Kottos and Gyges', 'Fighter'),
('Aerospace Center Defense', 'Multiple unidentified flying objects are approaching.', 'MiG-31 / SU-35 / B-2 Bombers / F-22+F-35B+YF-23 / F-15C / T-50', 'Fighter'),
('Aerospace Center Defense', 'Radar has detected the appoach of multiple slow moving targets.', 'B-2 Bombers  / Kottos and Gyges', 'Fighter'),
('Aerospace Center Defense', 'Radar sites in the vicinity have detected what it appears to be a stealth aircraft.', 'Il-76 and Escorts', 'Fighter'),
('Aerospace Center Defense', 'Reports indicate that enemy air forces equipped with special missiles are now in the air.', 'F-15C / F-14D / SU-35', 'Fighter'),
('Aerospace Center Defense', 'The shadow of a large object has been confirmed out at sea.', 'Scinfaxi', 'Attacker'),
('Pipeline Destruction', 'A large man-made structure has been spotted in the area.', 'Enemy Fleet', 'Attacker'),
('Pipeline Destruction', 'A radio report suggests that enemy cover operatives are active in the area.', 'Il-76 and Escorts', 'Fighter'),
('Pipeline Destruction', 'Confirmed multiple slow moving targets.', 'Enemy Fleet', 'Attacker'),
('Pipeline Destruction', 'Confirmed significant activity in enemy facilities.', 'F-14D / Cargo planes', 'Fighter'),
('Pipeline Destruction', 'Confirmed targets moving slowly and close to the ground.', 'Helicopters / Cargo planes', 'Fighter'),
('Pipeline Destruction', 'Enemy jamming signals detected.', 'Il-76 and Escorts', 'Fighter'),
('Pipeline Destruction', 'Intelligence suggests that new enemy weapons are being transported in the area.', 'Cargo planes / Scinfaxi', 'Multirole'),
('Pipeline Destruction', 'Locals have witnessed the shadows of large aircraft.', 'Il-76 and Escorts / Kottos and Gyges / Cargo Planes', 'Fighter'),
('Pipeline Destruction', 'Multiple unidentified flying objects are approaching.', 'MiG-31 / F14D / Helicopters / Su-35', 'Fighter'),
('Pipeline Destruction', 'Radar has detected the appoach of multiple slow moving targets.', 'Enemy Fleet / Helicopters', 'Attacker'),
('Pipeline Destruction', 'Reports indicate that enemy air forces equipped with special missiles are now in the air.', 'Su-35 / F-14D / F-15C', 'Fighter'),
('Pipeline Destruction', 'The shadow of a large object has been confirmed out at sea.', 'Scinfaxi / Enemy Fleet', 'Attacker'),
('Dubai Night Assault', 'Confirmed multiple enemy aircraft beyond the operations area.', 'Cruise missiles', 'Fighter'),
('Dubai Night Assault', 'Elite enemy air forces are approaching rapidly.', 'F-22 + F-35B + YF-23 / T-50', 'Fighter'),
('Dubai Night Assault', 'Enemy covert operatives are in the area.', 'F-35B Squadron', 'Fighter'),
('Dubai Night Assault', 'Intercepted information that enemy forces are hidden within the city.', 'F-35B VTOL / Airport battle', 'Multirole'),
('Dubai Night Assault', 'Multiple unidentified flying objects are approaching.', 'MiG-31 / Cruise missiles / F-15C / T-50 / F-35B / Su-35 / F-35B VTOL', 'Fighter'),
('Dubai Night Assault', 'Radar sites in the vicinity have detected what appears to be a stealth aircraft.', 'F-22 + F-35B + YF-23', 'Fighter'),
('Dubai Night Assault', 'Reports indicate that enemy air forces equipped with special missiles are now in the air.', 'MiG-31 / F-15C / T-50 / Su-35', 'Fighter'),
('Alps Air Corridor', 'A radio report suggests that enemy cover operatives are active in the area.', 'Il-76 and Escorts  / ECM radar sites + SP Planes', 'Multirole'),
('Alps Air Corridor', 'Elite enemy air forces are rapidly approaching.', 'F-22 + F-35B + YF-23 / T-50', 'Fighter'),
('Alps Air Corridor', 'Encrypted signals have been detected from enemy facilities.', 'ICBM / ECM radar sites + SP Planes', 'Attacker'),
('Alps Air Corridor', 'Enemies equipped with special weapons are in the air.', 'Su-35 / F-14 / F-15C / T-50', 'Fighter'),
('Alps Air Corridor', 'Enemy covert operatives are in the area.', 'ECM radar sites + SP planes', 'Attacker'),
('Alps Air Corridor', 'Enemy signals have been detected on enemy facilities.', 'ICBM', 'Multirole'),
('Alps Air Corridor', 'Ground forces are becoming more active.', 'ICBM', 'Multirole'),
('Alps Air Corridor', 'Intelligence suggests that new enemy weapons are being transported in the area.', 'Kottos and Gyges', 'Fighter'),
('Alps Air Corridor', 'Locals have witnessed the shadows of large aircraft.', 'Il-76 and Escorts / Kottos and Gyges', 'Fighter'),
('Alps Air Corridor', 'Multiple unidentified flying objects are approaching.', 'Il-76 and Escorts / T-50 / F-14D / F-22+F-35B+YF-23 / F-15C', 'Fighter'),
('Alps Air Corridor', 'Problems with radio communications in the area have been confirmed.', 'ECM radar sites + SP planes', 'Attacker'),
('Alps Air Corridor', 'Radar has detected the approach of multiple slow moving targets.', 'Kottos and Gyges', 'Fighter'),
('Alps Air Corridor', 'Radar sites in the vicinity have detected what appears to be a stealth aircraft.', 'F-22 + F-35B + YF-23', 'Fighter'),
('Alps Air Corridor', 'Reports indicate that enemy air forces equipped with special missiles are now in the air.', 'F-14D / F-15C', 'Fighter'),
('Alps Air Corridor', 'The enemy is operating some kind of special facilities.', 'ICBM', 'Multirole'),
('Weapons Base Assault', 'A radio report suggest that enemy cover operatives are active in the area', 'ECM radar sites + SP planes', 'Multirole'),
('Weapons Base Assault', 'Confirmed multiple slow moving targets.', 'Kottos and Gyges', 'Multirole'),
('Weapons Base Assault', 'Confirmed targets moving slowly and close to the ground.', 'Helicopters', 'Multirole'),
('Weapons Base Assault', 'Elite enemy air forces are rapidly approaching.', 'T-50 / F-22 + F-35B + YF-23', 'Fighter'),
('Weapons Base Assault', 'Encrypted signals have been detected from enemy facilities.', 'ICBM  / ECM radar sites', 'Multirole'),
('Weapons Base Assault', 'Intercepted information that enemy forces are hidding within the city.', 'ICBM', 'Fighter'),
('Weapons Base Assault', 'Local residents have witnessed the shadows of a large aircraft', 'Kottos and Gyges', 'Multirole'),
('Weapons Base Assault', 'Multiple unidentified flying objects are approaching.', 'Mig-31 / SU-35 / T-50 / Helicopters / F-22 + F-35B + YF-23 / K&G*', 'Fighter'),
('Weapons Base Assault', 'Problems with radio communications in the operation area have been confirmed.', 'ECM radar sites + SP planes', 'Attacker'),
('Weapons Base Assault', 'Radar has detected the approach of multiple slow moving targets.', 'Helicopters / Kottos and Gyges', 'Fighter'),
('Weapons Base Assault', 'Radar sites in the vicinity have detected what appears to be a stealth aircraft.', 'F-22 + F-35B + YF-23', 'Fighter'),
('Weapons Base Assault', 'Reports indicate that enemy air forces equipped with special missiles are now in the air.', 'SU-35 / MiG-31', 'Fighter'),
('Weapons Base Assault', 'The enemy is operating some kind of special facilities.', 'ICBM / ECM radar sites + SP planes', 'Multirole');
